language: cpp

compiler:
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libsdl2-dev libegl1-mesa-dev libgles2-mesa-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - cmake --build .
